# -*- coding: utf-8 -*-
"""exercicios for.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pz6Xxd7qURtQIWUSjrWejOeCinGjYQk4
"""

maior_numero = 0
for contador in range(5):
   numero = int(input("digite o primeiro numero"))
if numero > maior_numero:
    maior_numero = numero

print(maior_numero)

for contador in range(1000,2001):
  if contador % 11 ==2:
    print(contador )

soma = 0
for i in range(5):
  numero = float(input(f"digite o {i+1}º numero: "))
  soma += numero
media = soma/5
print(f"A soma dos numeros e: {soma}")
print(f"a media dos numeros e: {media}")

#Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número.
# Recebe o número do usuário
numero = int(input("Digite um número para calcular a tabuada: "))

# Calcula e mostra a tabuada usando um laço de repetição
print("Tabuada de", numero, ":")
for i in range(1, 11):
    resultado = numero * i
    print(numero, "x", i, "=", resultado)

# Calcula e mostra a tabuada usando um laço de repetição
for i in range(1, 11):
  for j in range(2, 20):
   resultado = i * j
   print(i, "x", j, "=", resultado)

#Faça um programa que imprima na tela os números de 1 a 20.
for i in range(1, 21):
  print(i)

#Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50
for contador in range(1,51):
 if contador % 2 == 1:
  print(contador)

#Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.

n1 = int(input("digite um numero:"))
n2 = int(input("digite outro numero: "))

for u in range(n1+1, n2):
  print(u)

lojaB = 54000
lojaA = 0

for i in range(5):
  valor = int(input("digite um valor"))
  lojaA += valor

if lojaA > lojaB:
  print("lojaA foi a maior")
elif lojaB == lojaA:
  print("valor igual")
else:
    print("LojaB foi a maior")

#Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares.

impar = 0
par = 0
for i in range(10):
  numero = int(input(f"digite o {i+1} numero inteiro "))
  if numero % 2 == 01:
    par += 2
  else:
    impar += 1


print(f"numeros impares = {impar} e numeros pares = {par}")

ano_contratacao = 1995
salario_inicial = 1000.00
percentual_aumento = 0.015  # 1.5% em decimal

for ano_atual in range(1996, 2025):  # considerando ate 2024
    salario_inicial += salario_inicial * percentual_aumento
    percentual_aumento *= 2  # Dobrando a porvetagem de aumento para o proximo ano
    print("O salário atual do funcionário é: R$", salario_inicial)

for i in range(3):
 nota = int(input("digite uma nota de 1 a 10"))
 if  nota > 0 and nota < 11:
  print("nota valida")
  break
 else:
  print("nota invalida, digite uma nota de 0 a 10")

print("Valor da Compra - Porcentagem de Desconto - Valor Final")

valor_base = 500

for desconto_porcentagem in range(1, 26):
    desconto_real = valor_base * (desconto_porcentagem / 100)
    valor_final = valor_base - desconto_real
    print(f"R${valor_base:.2f} - {desconto_porcentagem}% - R${valor_final:.2f}")


    valor_base += 100

ate_15_anos = 0
de_16_a_30_anos = 0
de_31_a_45_anos = 0
de_46_a_60_anos = 0
acima_de_61_anos = 0

# Recebendo as idades das 15 pessoas e contando quantas estão em cada faixa etária
for i in range(1, 16):
    idade = int(input(f"Digite a idade da pessoa {i}: "))
    if idade <= 15:
        ate_15_anos += 1
    elif 16 <= idade <= 30:
        de_16_a_30_anos += 1
    elif 31 <= idade <= 45:
        de_31_a_45_anos += 1
    elif 46 <= idade <= 60:
        de_46_a_60_anos += 1
    else:
        acima_de_61_anos += 1

# Calculando o total de pessoas
total_pessoas = 15

# Calculando a percentagem de pessoas na primeira e última faixa etária
percentagem_ate_15_anos = (ate_15_anos / total_pessoas) * 100
percentagem_acima_de_61_anos = (acima_de_61_anos / total_pessoas) * 100

# Exibindo os resultados
print("Quantidade de pessoas em cada faixa etária:")
print(f"Até 15 anos: {ate_15_anos}")
print(f"De 16 a 30 anos: {de_16_a_30_anos}")
print(f"De 31 a 45 anos: {de_31_a_45_anos}")
print(f"De 46 a 60 anos: {de_46_a_60_anos}")
print(f"Acima de 61 anos: {acima_de_61_anos}")

print("Porcentagem de pessoas na primeira e na última faixa etária:")
print(f"Até 15 anos: {percentagem_ate_15_anos:.2f}%")
print(f"Acima de 61 anos: {percentagem_acima_de_61_anos:.2f}%")

base = float(input("Digite a base: "))
expoente = int(input("Digite o expoente: "))

resultado = 1

for _ in range(expoente):
    resultado *= base

print(f"{base} elevado a {expoente} é igual a {resultado}")

N = int(input("Digite um número inteiro "))
primos = []
divisoes = 0

for num in range(2, N + 1):
    primo = True
    for i in range(2, int(num**0.5) + 1):
        divisoes += 1
        if num % i == 0:
            primo = False
            break
    if primo:
        primos += [num]

print("Números primos entre 1 e", N, primos)
print("Número total de divisões realizadas:", divisoes)

for i in range(3):
  break
x = int(input("coloque a quantidade de titulos da libertadores"))
if x == 3:
  print("vc acertou!!")
else:
  print("vc errou!!!")
y = int(input("coloque a quantidade de titulos do mundial"))
if y == 2:
  print("vc acertou!! boa peixudo")
else:
  print("vc errou!!, ai não heim")
z = int(input("coloque a quantidade de titulos do brasileiro"))
if z == 8:
  print("vc acertouu!!! parabens")
else:
  print("tente novamente")

ano_nascimento = 1926
ano_falecimento = 2022
idade = 0
for ano in range(ano_nascimento, ano_falecimento+1):
    idade = ano_falecimento - ano_nascimento

print("A idade que a Rainha Elizabeth Descansou Em Paz Foi Com", idade ,"anos de idade")
